/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,jsx}',
    './components/**/*.{js,jsx}',
    './app/**/*.{js,jsx}',
  ],
  theme: {
    extend: {
      colors: {
        background: '#FFFFFF',
        textPrimary: '#111827',
        textSecondary: '#6B7280',
        brandBlue: '#1E6BFF',
        brandDark: '#0F3D91',
        accent: '#3B82F6',
        inputBorder: '#E5E7EB',
        inputBorderFocus: '#2563EB',
        buttonBg: '#1E6BFF',
        buttonBgHover: '#1A5EE0',
        buttonBgDisabled: '#E5E7EB',
        buttonText: '#FFFFFF',
        chipBg: '#F9FAFB',
        divider: '#F3F4F6',
        shadow: 'rgba(0,0,0,0.06)',
      },
      fontFamily: {
        sans: [
          '-apple-system',
          'BlinkMacSystemFont',
          "'Segoe UI'",
          'Roboto',
          'Inter',
          "'Helvetica Neue'",
          'Arial',
          "'Noto Sans'",
          "'Apple Color Emoji'",
          "'Segoe UI Emoji'",
          "'Segoe UI Symbol'",
          "'Noto Color Emoji'",
        ],
      },
      fontSize: {
        xs: '12px',
        sm: '14px',
        base: '16px',
        lg: '18px',
        xl: '20px',
        '2xl': '24px',
        '3xl': '28px',
        '4xl': '32px',
        '5xl': '40px',
      },
      lineHeight: {
        tight: '1.15',
        snug: '1.3',
        normal: '1.5',
      },
      borderRadius: {
        xs: '6px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '20px',
      },
      spacing: {
        '0': '0',
        '1': '4px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '5': '20px',
        '6': '24px',
        '7': '28px',
        '8': '32px',
        '10': '40px',
        '12': '48px',
        '16': '64px',
        '20': '80px',
        '24': '96px',
      },
      boxShadow: {
        sm: '0 1px 2px rgba(0,0,0,0.05)',
        md: '0 10px 24px rgba(0,0,0,0.08)',
        button: '0 6px 16px rgba(30,107,255,0.25)',
      },
      screens: {
        sm: '360px',
        md: '768px',
        lg: '1280px',
      },
      maxWidth: {
        containerSm: '560px',
        containerMd: '720px',
        containerLg: '960px',
        buttonSm: '560px',
        buttonMd: '420px',
        buttonLg: '420px',
      },
      width: {
        pinCellSm: '56px',
        pinCellMd: '64px',
        pinCellLg: '68px',
        langChip: '40px',
      },
      height: {
        pinCellSm: '56px',
        pinCellMd: '64px',
        pinCellLg: '68px',
        buttonHSm: '52px',
        buttonHMd: '56px',
        buttonHLg: '56px',
        langChip: '40px',
        logoHSm: '28px',
        logoHMd: '32px',
        logoHLg: '56px',
      },
    },
  },
  plugins: [],
}

